configs: configs_cloud.yaml

experiment:
  use_trace: 1
  trace: /home/zhijian/workspace_fast/Monax/traces/mahimahi/trace/subset/report_bus_0001.log
  base_delay: 20
  control_interval: 0.003
  running_time: 10





