configs: configs_cloud.yaml

experiment:
  use_trace: 1
  # trace: /home/zhijian/workspace_fast/Monax/traces/mahimahi/trace/subset/report_bus_0001.log
  trace: /home/zhijian/workspace_fast/Monax/traces/mahimahi/trace/static/96mbps.log
  base_delay: 1
  control_interval: 0.01
  running_time: 10





